[package]
name = "rsmenuu"
version = "0.1.0"
edition = "2021"
authors = ["ErickDevv"]
description = "Create menus easily on your terminal using Rust"
license = "MIT"

[dependencies]
ncurses = "5.101.0"